### ISSUE TITLE
🐛 [Google format] ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by astariul** [rr-/docstring_parser#37]
I have a `ValueError` exception when running the following code :

```python
from docstring_parser import parse

def x():
    """Example Google style docstrings.

    This module demonstrates documentation as specified by the `Google Python
    Style Guide`_. Docstrings may extend over multiple lines. Sections are created
    with a section header and a colon followed by a block of indented text.

    Example:
        Examples can be given using either the ``Example`` or ``Examples``
        sections. Sections support any reStructuredText formatting, including
        literal blocks::
            $ python example_google.py

    Section breaks are created by resuming unindented text. Section breaks
    are also implicitly created anytime a new section starts.

    Attributes:
        module_level_variable1 (int): Module level variables may be documented in
            either the ``Attributes`` section of the module docstring, or in an
            inline docstring immediately following the variable.
            Either form is acceptable, but the two should not be mixed. Choose
            one convention to document module level variables and be consistent
            with it.

    Todo:
        * For module TODOs
        * You have to also use ``sphinx.ext.todo`` extension
        
    .. _Google Python Style Guide:
    http://google.github.io/styleguide/pyguide.html
    """
    pass

parse(x.__doc__)
```

Traceback :

> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\remon\Documents\workspace\docution\docution\__init__.py", line 85, in test
    docstring = parse(obj.__doc__)
  File "C:\Users\remon\AppData\Local\Programs\Python\Python38-32\lib\site-packages\docstring_parser\parser.py", line 20, in parse
    rets.append(parse_(text))
  File "C:\Users\remon\AppData\Local\Programs\Python\Python38-32\lib\site-packages\docstring_parser\google.py", line 274, in parse
    return GoogleParser().parse(text)
  File "C:\Users\remon\AppData\Local\Programs\Python\Python38-32\lib\site-packages\docstring_parser\google.py", line 264, in parse
    ret.meta.append(self._build_meta(part, title))
  File "C:\Users\remon\AppData\Local\Programs\Python\Python38-32\lib\site-packages\docstring_parser\google.py", line 106, in _build_meta
    before, desc = text.split(":", 1)
**ValueError: not enough values to unpack (expected 2, got 1)**

**Comment by mayeroa** [comment]
I met the same issue trying to extract docstrings from PyTorch loss classes.
Here a minimal repro:

```python
import torch
from docstring_parser import parse

parse(torch.nn.modules.loss.BCELoss.__doc__)
```

And the error:

```shell
>>> parse(torch.nn.modules.loss.BCELoss.__doc__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]/python3.6/site-packages/docstring_parser/parser.py", line 20, in parse
    rets.append(parse_(text))
  File "[...]/python3.6/site-packages/docstring_parser/google.py", line 274, in parse
    return GoogleParser().parse(text)
  File "[...]/python3.6/site-packages/docstring_parser/google.py", line 264, in parse
    ret.meta.append(self._build_meta(part, title))
  File "[...]/python3.6/site-packages/docstring_parser/google.py", line 106, in _build_meta
    before, desc = text.split(":", 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

Any idea?

**Comment by rr-** [comment]
Please try version 0.8.
